### ISSUE TITLE
Add proper bower support

### ISSUE THREAD

**Issue by JBlaak** [DJWassink/Animated-material-floatbutton#1]
Currently this (awesome) animation set isn't usable as bower dependency, please namespace classes and no styling of global elements. Maybe a separate `example` dir with the required styling/scripting to make that work?

**Comment by DJWassink** [comment]
Css rules are now namespaced under `animated-material-fab` and you can install it through bower with `bower install animated-material-floatbutton`, enjoy!

**Comment by JBlaak** [comment]
Awesome! Thanks!
